### ISSUE TITLE
Readme File Update

### ISSUE THREAD

**Issue by tjsiledar** [rktamplayo/AceSum#3]
@rktamplayo Thank you for such awesome work. Can you please also update the readme file. Would be of great help to reproduce the code. Thanks in advance!

**Comment by rktamplayo** [comment]
Sorry for the long wait, and thanks for bugging me. Due to personal reasons, I had to skip this on my to-do list. Everything is updated with README and all the data/model/output files you need!

**Comment by patrycjakarolina** [comment]
Thanks a lot, that's very helpful! 

I managed to successfully train MIL model on space data, but training on my dataset fails. Dataset also contains reviews with difference that there is much higher number of aspects in comparison to space dataset - 35 aspects. During training, loss is being minimised but F1 score converges from ~0.04 to 0 after few hundred epochs. Have you tried training MIL model on dataset with more aspects? Are there any changes in the architecture related to increased number of aspects (number of heads, number of layers) that are crucial to achieve good performance?


Looking forward to your answer :)

**Comment by rktamplayo** [comment]
Have you tried increasing the number of heads to greater than your #aspects (e.g. to 48)? One reason why I divided oposum MIL into subdomains is because 6*3=18 aspects is too much for the model to handle. But I would try to increase the heads (+ maybe the hidden dims as well)

**Comment by patrycjakarolina** [comment]
Yeah, I tried it by it didn't help. I've done an experiment and cut down to 8 and 3 themes, but situation looks the same. Training starts from relatively high per document and per sentence F1 scores (e.g.  for three aspects - document F1 is 0.3553 and sentence F1 is 0.3662) but they decrease to 0 after 1000-1200 train steps (the more aspects the lower initial F1 score and they converge to 0 faster). Although, my topic are less exclusive e.g. instead of "room" and "location" I have "room: decor" and "room: cleanliness". 

Do you think that exclusiveness of aspects might be the reason for such behaviour?

Many thanks for your answers!
